{{- if .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "prom-monitor-{{ template "agent-assist.fullname" . }}-frontend"
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      role: frontend
{{- end }}