{{- if .Values.genesysNotificationsForwarder.enabled -}}
{{- if (not .Values.genesysNotificationsForwarder.apiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: agent-assist-genesys-notifications-forwarder-api-key
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  # this should contain a valid api key for the Agent Assist API
  api-key: {{ .Values.genesysNotificationsForwarder.apiKey.value | b64enc | quote }}
{{- end }}
{{- end }}