{{- if (not .Values.backend.apiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: agent-assist-api-key
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  # this should contain a valid api key for the Agent Assist API
  api-key: {{ .Values.backend.apiKey.value | b64enc | quote }}
{{- end }}
