{{- if .Values.genesysNotificationsForwarder.enabled -}}
{{- if (not .Values.genesysNotificationsForwarder.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: agent-assist-genesys-cloud-credentials
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  # this should contain a valid api key for the Agent Assist API
  client-id: {{ .Values.genesysNotificationsForwarder.credentials.clientId.value | b64enc | quote }}
  client-secret: {{ .Values.genesysNotificationsForwarder.credentials.clientSecret.value | b64enc | quote }}
{{- end }}
{{- end }}