{{- if (not .Values.backend.cognigyServiceEndpointApiAccessToken.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-service-endpoint-api-access-token
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  # this should contain a valid api key for the Agent Assist API
  api-access-token: {{ .Values.backend.cognigyServiceEndpointApiAccessToken.value | b64enc | quote }}
{{- end }}
