{{- if .Values.frontend.enabled -}}
{{- if .Values.frontend.ingress.enabled -}}
{{- $ingressApiIsStable := eq (include "grafana.ingress.isStable" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "grafana.ingress.supportsPathType" .) "true" -}}
apiVersion: {{ include "grafana.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "agent-assist-frontend.fullname" . }}
  labels:
    {{- include "agent-assist.selectorLabels" . | nindent 4 }}
  {{- if .Values.frontend.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.frontend.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: traefik
  {{- if .Values.frontend.ingress.tls }}
  tls:
    {{- range .Values.frontend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
            {{- if $ingressApiIsStable }}
              service:
                name: {{ .backend.service.name }}
                port:
                  number: {{ int .backend.service.port.number }}
            {{- else }}
              serviceName: {{ .backend.service.name }}
              servicePort: {{ int .backend.service.port.number }}
            {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}